
name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CPU PyTorch
        if: ${{ matrix.os != 'macos-latest' }}
        run: pip3 install torch==2.1.2 --index-url https://download.pytorch.org/whl/cpu
      - name: Install PyTorch on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: pip3 install torch==2.1.2
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Check code style
        run: ruff check .
      - name: Test
        run: pytest
      - name: Upload coverage
        uses: codecov/codecov-action@v3
